server.port=8080
spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Discovery locator ? encontra serviços automaticamente pelo Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Rotas
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=personagens-service
spring.cloud.gateway.routes[1].uri=lb://personagens-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/personagens/**

spring.cloud.gateway.routes[2].id=inventario-service
spring.cloud.gateway.routes[2].uri=lb://inventario-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/inventario/**,/itens/**

spring.cloud.gateway.routes[3].id=combate-service
spring.cloud.gateway.routes[3].uri=lb://combate-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/batalha/**