server.port=8082
spring.application.name=combate-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Feign
spring.cloud.openfeign.enabled=true

# H2 Console
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:combatedb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect